In [3]:
import csv
with open('practice.csv','r') as csv_file:
    data = csv.reader(csv_file)
    for row in data:
        print(','.join(row))

department_id,department_name,manager_id,location_id
10,Administration,200,1700
20,Marketing,201,1800
30,Purchasing,114,1700
40,Human Resources,203,2400
50,Shipping,121,500
60,IT,103,1400


In [4]:
import csv
with open('practice.csv', 'r') as file:
    reader = csv.reader(file, delimiter = '\t')
    for row in reader:
        print(row)

['department_id,department_name,manager_id,location_id']
['10,Administration,200,1700']
['20,Marketing,201,1800']
['30,Purchasing,114,1700']
['40,Human Resources,203,2400']
['50,Shipping,121,500']
['60,IT,103,1400']


In [16]:
total_col_1=0
total_col_2=0
total_row=0
with open("my_num.csv",'r') as file:
    data = csv.reader(file)
    fields = next(data)
    for row in data:
        #print(row[1])
        #print(row[0])
        total_col_1 += int(row[0])
        total_col_2 += int(row[1])
        total_row += int(row[0])+int(row[1])
print(total_row)
print(total_col_1)
print(total_col_2)

2608
1211
1397


In [19]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
number_gt = []
#number_gt = [x for x in a if x>3]
print("Values bigger than 3 =", a[a>3])

Values bigger than 3 = [4 5 6 7 8 9]


In [23]:
import csv
with open('practice.csv', newline='') as f:
    reader = csv.reader(f)
    data_list = list(reader)
print(data_list)

[['department_id', 'department_name', 'manager_id', 'location_id'], ['10', 'Administration', '200', '1700'], ['20', 'Marketing', '201', '1800'], ['30', 'Purchasing', '114', '1700'], ['40', 'Human Resources', '203', '2400'], ['50', 'Shipping', '121', '500'], ['60', 'IT', '103', '1400']]


In [24]:
import csv
data = csv.DictReader(open("practice.csv"))
print("CSV file as a dictionary:\n")
for row in data:
    print(row)

CSV file as a dictionary:

{'department_id': '10', 'department_name': 'Administration', 'manager_id': '200', 'location_id': '1700'}
{'department_id': '20', 'department_name': 'Marketing', 'manager_id': '201', 'location_id': '1800'}
{'department_id': '30', 'department_name': 'Purchasing', 'manager_id': '114', 'location_id': '1700'}
{'department_id': '40', 'department_name': 'Human Resources', 'manager_id': '203', 'location_id': '2400'}
{'department_id': '50', 'department_name': 'Shipping', 'manager_id': '121', 'location_id': '500'}
{'department_id': '60', 'department_name': 'IT', 'manager_id': '103', 'location_id': '1400'}
