In [2]:
import numpy as np
a = np.arange(6)
print(a)
print(a.shape)

[0 1 2 3 4 5]
(6,)


In [3]:
a = np.arange(6).reshape(2,3)

In [4]:
print(a)

[[0 1 2]
 [3 4 5]]


In [5]:
print(a.shape)

(2, 3)


In [6]:
print(a.size)
print(a.ndim) #
print(a.dtype) # type of the nu,py array
print(a.itemsize) # size of each element in byted

6
2
int32
4


In [7]:
b = ([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
print(b)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.ones((2,3,4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
print(np.ones((2,3,4),dtype = np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [13]:
print(np.arange(4,40,4))

[ 4  8 12 16 20 24 28 32 36]


In [14]:
print(np.arange(4,40,-4))

[]


In [15]:
print(np.arange(40,4,4))

[]


In [16]:
print(np.arange(40,4,-4))

[40 36 32 28 24 20 16 12  8]


In [17]:
a = np.arange(10)
print(a)
print('sqaure of a=',a**2)
print(a>5)

[0 1 2 3 4 5 6 7 8 9]
sqaure of a= [ 0  1  4  9 16 25 36 49 64 81]
[False False False False False False  True  True  True  True]


In [18]:
b = np.random.random((3,4))
print(b)

[[0.25957134 0.92837659 0.37313296 0.6724314 ]
 [0.34309408 0.83311386 0.28080021 0.91919149]
 [0.99767646 0.43690318 0.31782318 0.3363918 ]]


In [19]:
print('sum',b.sum())
print('max',b.max())

sum 6.6985065400219055
max 0.9976764602068887


In [20]:
arr = np.array([[1,2,3],[4,5,6]])
flat= arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [22]:
digits = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(digits)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
import numpy as np
CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
print("grades before averaging ",grades)
def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    print("grades before clipping",new_grades)
    return np.clip(new_grades, grades, 100)

print("grades after change ", curve(grades))

grades before averaging  [72 35 64 88 51 90 74 12]
grades before clipping [ 91.25  54.25  83.25 107.25  70.25 109.25  93.25  31.25]
grades after change  [ 91  54  83 100  70 100  93  31]


In [53]:
b = np.arange(10)
print(b)
avg = b.mean()
change = 5-avg
b_change = b+change
print(np.clip(b_change,b,8,))
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.  8. ]
[0 1 2 3 4 5 6 7 8 9]


In [58]:
a = np.arange(10)
print("clipped array " ,np.clip(a, 1, 8))

print("original array ",a)



clipped array  [1 1 2 3 4 5 6 7 8 8]
original array  [0 1 2 3 4 5 6 7 8 9]


In [61]:
print(np.clip(a, 3, 6, out=a))
print(a)#modified

[3 3 3 3 4 5 6 6 6 6]
[3 3 3 3 4 5 6 6 6 6]


In [73]:
a = np.arange(10)
print(a)
b = [3, 4, 5, 1, 1, 4, 4, 4, 4, 4]
print(b)
print(np.clip(b,a,8))


[0 1 2 3 4 5 6 7 8 9]
[3, 4, 5, 1, 1, 4, 4, 4, 4, 4]
[3 4 5 3 4 5 6 7 8 8]


In [24]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(np.clip(a,1,8,out = a))
print(a)


[1 1 2 3 4 5 6 7 8 8]
[1 1 2 3 4 5 6 7 8 8]
[1 1 2 3 4 5 6 7 8 8] [1 1 2 3 4 5 6 7 8 8] 8


In [94]:
import numpy as np

temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2
]).reshape(2, 2, 3)

print(temperatures.shape)
print(temperatures)

(2, 2, 3)
[[[29.3 42.1 18.8]
  [16.1 38.  12.5]]

 [[12.6 49.9 38.6]
  [31.3  9.2 22.2]]]


In [95]:
temperatures = np.swapaxes(temperatures, 1, 2)
print(temperatures)

[[[29.3 16.1]
  [42.1 38. ]
  [18.8 12.5]]

 [[12.6 31.3]
  [49.9  9.2]
  [38.6 22.2]]]


In [96]:
temperatures.shape

(2, 3, 2)

In [78]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [101]:
table =np.array([
    [0,1,1,4,5],
    [6,7,8,9,0],
    [3,4,5,6,7],
    [1,2,3,-1,5],
    [3,4,5,7,8]
])

In [102]:
table.max()

9

In [103]:
table.max(axis=0)#vertical columnwise max element

array([6, 7, 8, 9, 8])

In [105]:
table.max(axis=1) #horizontal rowwise max element

array([5, 9, 7, 5, 8])

In [106]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

In [1]:
import numpy as np

In [2]:
c = np.full((2,2),6)

In [3]:
c

array([[6, 6],
       [6, 6]])